# Generated by Django 5.1.7 on 2025-03-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='plant',
        ),
    ]
